llama_endpoint: http://localhost:11434
storage:
  tmp: tmp
runtime:
  default:
    model: llava:13b
    fps: 0.25
    allow_single_frame: true
    temperature: 0.3
    prompt: "Describe the contents of this image."